  hassio:
    image: "homeassistant/home-assistant:latest"
    container_name: "hassio"
    restart: unless-stopped
    network_mode: host
    depends_on:
      - influxdb
      - mosquitto
    ports:
      - 8123:8123
    volumes:
      - ./volumes/hassio/config:/config
      - /etc/localtime:/etc/localtime:ro
    #environment:
    #  - TZ=${HOST_TZ}
