site_name: IOTstack
site_description: 'Docker stack for getting started on IOT on the Raspberry PI'
theme:
  name: material
plugins:
  - search
# - awesome-pages
markdown_extensions:
  - pymdownx.superfences
