mosquitto:
  container_name: mosquitto
  build:
    context: ./.templates/mosquitto/.
    args:
    - MOSQUITTO_BASE=eclipse-mosquitto:latest
  restart: unless-stopped
  environment:
    - TZ=Etc/UTC
  ports:
    - "1883:1883"
  volumes:
    - ./volumes/mosquitto/config:/mosquitto/config
    - ./volumes/mosquitto/data:/mosquitto/data
    - ./volumes/mosquitto/log:/mosquitto/log
    - ./volumes/mosquitto/pwfile:/mosquitto/pwfile

