  webthings_gateway:
    image: mozillaiot/gateway:arm
    container_name: webthings_gateway
    network_mode: host
    #ports:
    # - 8080:8080
    # - 4443:4443
    #devices:
    # - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ./volumes/webthings_gateway/share:/home/node/.mozilla-iot

      