domoticz:
  container_name: domoticz
  image: linuxserver/domoticz:stable
  ports:
    - "8080:8080"
    - "6144:6144"
    - "1443:1443"
  volumes:
    - ./volumes/domoticz/data:/config
  restart: unless-stopped
  network_mode: bridge
  environment:
    - PUID=1000
    - PGID=1000
    # - TZ=
    # - WEBROOT=domoticz
