pihole:
  container_name: pihole
  image: pihole/pihole:latest
  ports:
    - "8089:80/tcp"
    - "53:53/tcp"
    - "53:53/udp"
    - "67:67/udp"
  environment:
    - WEBPASSWORD=%randomAdminPassword%
    - INTERFACE=eth0
  volumes:
      - ./volumes/pihole/etc-pihole:/etc/pihole
      - ./volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
  dns:
    - 127.0.0.1
    - 1.1.1.1
  cap_add:
    - NET_ADMIN
  restart: unless-stopped
  networks:
    - iotstack_nw
    - vpn_nw

# Recommended but not required (DHCP needs NET_ADMIN)
#   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities