diyhue:
  container_name: diyhue
  image: diyhue/core:latest
  ports:
    - "8070:80/tcp"
    - "1900:1900/udp"
    - "1982:1982/udp"
    - "2100:2100/udp"
  environment:
    - IP=%LAN_IP_Address%
    - MAC=%LAN_MAC_Address%
  volumes:
      - ./volumes/diyhue:/opt/hue-emulator/export
  restart: unless-stopped

