homebridge:
  container_name: homebridge
  image: oznu/homebridge:latest
  restart: unless-stopped
  environment:
    - TZ=Etc/UTC
    - PGID=1000
    - PUID=1000
    - HOMEBRIDGE_CONFIG_UI=1
    - HOMEBRIDGE_CONFIG_UI_PORT=8581
  volumes:
    - ./volumes/homebridge:/homebridge
  network_mode: host

