  blynk_server:
    build: ./services/blynk_server/.
    container_name: blynk_server
    restart: unless-stopped
    ports:
      - "8180:8080"
      - "8441:8441"
      - "9443:9443"
    volumes:
      - ./volumes/blynk_server/data:/data
      - ./volumes/blynk_server/data/config:/config
