telegraf:
  container_name: telegraf
  build: ./.templates/telegraf/.
  hostname: iotstack # optional
  restart: unless-stopped
  environment:
    - TZ=Etc/UTC
  ports:
    - "8092:8092/udp"
    - "8094:8094/tcp"
    - "8125:8125/udp"
  volumes:
    - ./volumes/telegraf:/etc/telegraf
    - /var/run/docker.sock:/var/run/docker.sock:ro
  depends_on:
    - influxdb
    - mosquitto

