  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 9321:80
    volumes:
      - ./volumes/nextcloud/html:/var/www/html:rw
    restart: unless-stopped
    depends_on: 
      - nextcloud_db
    links:
      - nextcloud_db
    networks:
      - iotstack_nw
      - nextcloud_internal
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_PASSWORD=%randomMySqlPassword% # %randomMySqlPassword% is overwritten during preBuild hook
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  nextcloud_db:
    image: linuxserver/mariadb
    # command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: nextcloud_db
    volumes:
      - ./volumes/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=%randomPassword% # %randomPassword% is overwritten during preBuild hook
      - MYSQL_PASSWORD=%randomMySqlPassword% # %randomMySqlPassword% is overwritten during preBuild hook
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
    networks:
      - nextcloud_internal
    logging:
      options:
        max-size: "5m"
        max-file: "3"
