python:
  container_name: python
  build: ./services/python/.
  restart: unless-stopped
  environment:
    - TZ=Etc/UTC
    - IOTSTACK_UID=1000
    - IOTSTACK_GID=1000
  # ports:
  #   - "external:internal"
  volumes:
    - ./volumes/python/app:/usr/src/app

