  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    environment:
      POSTGRES_USER=postuser
      POSTGRES_PASSWORD=postpassword
      POSTGRES_DB=postdb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/timescaledb/data:/var/lib/postgresql/data
    networks:
      - iotstack_nw
    logging:
      options:
        max-size: "5m"
        max-file: "3"